export const STRINGS = {
  ru: {
    // Onboarding
    welcome:           'Добро пожаловать!',
    welcome_sub:       'Давайте познакомимся',
    enter_name:        'Как вас зовут?',
    name_placeholder:  'Введите ваше имя',
    choose_language:   'Выберите язык:',
    continue_btn:      'Продолжить',
    name_required:     'Пожалуйста, введите ваше имя',

    // Main screen button labels
    btn_idle:          'Нажмите',
    btn_listening:     'Слушаю...',
    btn_speaking:      'Говорю...',
    btn_thinking:      'Думаю...',
    btn_farewell:      'До свидания...',
    tap_to_end:        'Нажмите снова, чтобы завершить',

    // Errors / notices
    no_internet:       'Нет подключения к интернету. Пожалуйста, проверьте связь.',
    api_error:         'Произошла ошибка. Попробуйте ещё раз.',
    mic_denied:        'Пожалуйста, разрешите доступ к микрофону в настройках браузера.',
    no_speech_support: 'Пожалуйста, используйте браузер Google Chrome для голосового общения.',

    // Settings
    settings_title:    'Настройки',
    settings_name:     'Ваше имя',
    settings_language: 'Язык',
    settings_mode:     'Режим разговора',
    fast_mode:         'Быстрый режим',
    fast_mode_desc:    'Быстрые и короткие ответы',
    smart_mode:        'Умный режим',
    smart_mode_desc:   'Подробные и вдумчивые ответы',
    reminders_title:   'Активные напоминания',
    no_reminders:      'Нет активных напоминаний',
    delete_btn:        'Удалить',
    clear_history:     'Очистить историю разговоров',
    clear_title:       'Удалить историю?',
    clear_confirm:     'Вся история разговоров будет удалена. Продолжить?',
    clear_yes:         'Да, удалить',
    clear_no:          'Отмена',
    save_btn:          'Сохранить',
    saved_msg:         '✓ Сохранено!',
    back_btn:          '← Назад',
    chrome_note:       'Приложение лучше всего работает в браузере Google Chrome.',
    reminder_at:       'в',
    reminder_daily:    'каждый день',

    // Personal info
    personal_title:         'О вас',
    personal_birthday:      'День рождения',
    personal_day:           'День',
    personal_month:         'Месяц',
    personal_year:          'Год',
    personal_year_ph:       'например, 1945',
    personal_children:      'Имена детей',
    personal_children_ph:   'например: Михаил, Ольга',
    personal_grandchildren: 'Имена внуков',
    personal_grandchildren_ph: 'например: Саша, Катя, Дима',
    personal_great:         'Имена правнуков',
    personal_great_ph:      'например: Петя',
    months: ['Январь','Февраль','Март','Апрель','Май','Июнь',
             'Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'],
  },

  he: {
    // Onboarding
    welcome:           'ברוך הבא!',
    welcome_sub:       'בואו נכיר',
    enter_name:        'מה שמך?',
    name_placeholder:  'הכנס את שמך',
    choose_language:   'בחר שפה:',
    continue_btn:      'המשך',
    name_required:     'אנא הכנס את שמך',

    // Main screen button labels
    btn_idle:          'לחץ',
    btn_listening:     'מקשיב...',
    btn_speaking:      'מדבר...',
    btn_thinking:      'חושב...',
    btn_farewell:      'להתראות...',
    tap_to_end:        'לחץ שוב לסיום השיחה',

    // Errors / notices
    no_internet:       'אין חיבור לאינטרנט. אנא בדוק את החיבור.',
    api_error:         'אירעה שגיאה. נסה שוב.',
    mic_denied:        'אנא אפשר גישה למיקרופון בהגדרות הדפדפן.',
    no_speech_support: 'אנא השתמש בדפדפן Google Chrome לשיחה קולית.',

    // Settings
    settings_title:    'הגדרות',
    settings_name:     'שמך',
    settings_language: 'שפה',
    settings_mode:     'מצב שיחה',
    fast_mode:         'מצב מהיר',
    fast_mode_desc:    'תגובות מהירות וקצרות',
    smart_mode:        'מצב חכם',
    smart_mode_desc:   'תגובות מפורטות ומחושבות',
    reminders_title:   'תזכורות פעילות',
    no_reminders:      'אין תזכורות פעילות',
    delete_btn:        'מחק',
    clear_history:     'נקה היסטוריית שיחות',
    clear_title:       'למחוק היסטוריה?',
    clear_confirm:     'כל היסטוריית השיחות תימחק. להמשיך?',
    clear_yes:         'כן, מחק',
    clear_no:          'ביטול',
    save_btn:          'שמור',
    saved_msg:         '✓ נשמר!',
    back_btn:          'חזרה →',
    chrome_note:       'האפליקציה עובדת הכי טוב בדפדפן Google Chrome.',
    reminder_at:       'ב-',
    reminder_daily:    'כל יום',

    // Personal info
    personal_title:         'עליך',
    personal_birthday:      'יום הולדת',
    personal_day:           'יום',
    personal_month:         'חודש',
    personal_year:          'שנה',
    personal_year_ph:       'לדוגמה: 1945',
    personal_children:      'שמות הילדים',
    personal_children_ph:   'לדוגמה: מיכאל, אולגה',
    personal_grandchildren: 'שמות הנכדים',
    personal_grandchildren_ph: 'לדוגמה: סשה, קטיה, דימה',
    personal_great:         'שמות הנינים',
    personal_great_ph:      'לדוגמה: פטיה',
    months: ['ינואר','פברואר','מרץ','אפריל','מאי','יוני',
             'יולי','אוגוסט','ספטמבר','אוקטובר','נובמבר','דצמבר'],
  },
};
