export const COLORS = {
  background:       '#FFF8F0',
  settingsBg:       '#FFF3E8',
  text:             '#3B2A1A',
  textLight:        '#6B5040',
  textMuted:        '#9B8070',
  white:            '#FFFFFF',
  buttonIdle:       '#E8845A',
  buttonHover:      '#D46A42',
  buttonActive:     '#C4634A',
  buttonSpeaking:   '#8B6F5E',
  buttonThinking:   '#A88070',
  error:            '#C0392B',
  errorBg:          '#FFF0F0',
  errorBorder:      '#F5C0C0',
  inputBg:          '#FFF0E0',
  inputBorder:      '#D4B89A',
  divider:          '#E8D0BC',
  reminderBg:       '#FFF4ED',
  modelActiveBg:    '#FFF0E8',
  modelActiveBorder:'#E8845A',
  successGreen:     '#5A9E6A',
};

export const SIZES = {
  buttonPx:     220,
  titleFont:    36,
  largeFont:    28,
  mediumFont:   24,
  smallFont:    20,
  xsmallFont:   18,
  labelFont:    28,
  bodyMin:      22,
};
